### ISSUE TITLE
Implement Aggregate Task Type

### ISSUE THREAD

**Issue by pedronauck** [compozy/go-orchestrator#39]
## Overview

Implement a new "aggregate" task type that combines results from multiple tasks into a single output using template-based transformations. This task type is purely template-driven and leverages existing infrastructure.

#### Core Infrastructure

* ✅ Added `TaskTypeAggregate` constant to task types
* ✅ Updated execution type mapping to use basic execution for aggregate tasks
* ✅ Created comprehensive validation logic for aggregate tasks

#### Validation & Security

* ✅ Aggregate tasks must have `outputs` defined
* ✅ Aggregate tasks cannot have `action`, `agent`, `tool`, `sleep`, or `with` fields
* ✅ Added schema validation for processed aggregate outputs
* ✅ Template syntax validation during task configuration

#### Execution Logic

* ✅ Created `ExecuteAggregate` activity with timeout protection (30s default)
* ✅ Template-only execution using existing `ConfigNormalizer`
* ✅ Proper context propagation for workflow-level template access
* ✅ Goroutine leak prevention in timeout handling

#### Workflow Integration

* ✅ Registered aggregate activity in Temporal worker
* ✅ Added routing logic in workflow execution
* ✅ Full integration with existing task lifecycle

#### Testing & Documentation

* ✅ Comprehensive test coverage for validation and configuration
* ✅ YAML test fixtures demonstrating various aggregation patterns
* ✅ Detailed implementation plan document

#### Reviews Completed

* ✅ **Gemini Code Review**: Comprehensive analysis of code quality and standards
* ✅ **O3 Code Review**: Deep logic analysis and edge case detection
* ✅ **Pre-commit Validation**: Full validation of changes before commit

#### Critical Issues Fixed

* ✅ **Goroutine Leak**: Fixed timeout handling to prevent resource leaks
* ✅ **Context Propagation**: Ensured proper context flow for cancellation
* ✅ **WorkflowConfig Bug**: Fixed critical nil workflow config that would break templates
* ✅ **Schema Validation**: Added output validation against defined schemas

### Basic Aggregation

```yaml
id: combine-results
type: aggregate

outputs:
  total: "{{ add .tasks.count_users.output.count .tasks.count_orders.output.count }}"
  summary: "Found {{ .total }} total items"

on_success:
  next: next-task
```

### Complex Aggregation

```yaml
id: comprehensive-summary
type: aggregate

outputs:
  metrics:
    user_count: "{{ .tasks.count_users.output.count }}"
    order_count: "{{ .tasks.count_orders.output.count }}"
    success_rate: "{{ div .tasks.count_users.output.successful (add .tasks.count_users.output.successful .tasks.count_users.output.failed) }}"

  status: "{{ if gt .tasks.count_users.output.failed 0 }}warning{{ else }}success{{ end }}"

  details:
    timestamp: "{{ now }}"
    processed_by: "{{ .workflow.id }}"
    execution_id: "{{ .workflow.execution_id }}"
```

### Architecture Benefits

1. **Simplicity**: No new struct required, uses existing `BaseConfig.Outputs`
2. **Consistency**: Follows established task patterns and validation
3. **Reusability**: Leverages existing template engine and infrastructure
4. **Performance**: Lightweight execution with proper timeout protection
5. **Security**: Inherits template sandboxing and validation

### Files Modified

* `engine/task/config.go` - Added aggregate task type
* `engine/task/validators.go` - Added comprehensive validation
* `engine/task/activities/exec_aggregate.go` - Core execution logic
* `engine/worker/*` - Workflow integration and registration
* Test fixtures and documentation

## Commit Details

* **Branch**: `pn/task-aggregate`
* **Commit**: `1079119` - feat: implement aggregate task type
* **Files Changed**: 11 files, 851 insertions, 17 deletions
* **Quality**: All tests passing, lint clean, comprehensive reviews completed

## Next Steps

- [ ] Merge PR #38
- [ ] Update documentation
- [ ] Create example workflows using aggregate tasks
