### ISSUE TITLE
Three-Tier Memory Configuration Resolution Implementation

### ISSUE THREAD

**Issue by pedronauck** [compozy/go-orchestrator#91]
# Three-Tier Memory Configuration Resolution Implementation

## Objective

Implement corrected configuration resolution for all three complexity levels.

## Implementation Steps

1. Create `ConfigurationResolver` with registry dependency injection
2. Implement `ResolveMemoryConfig` with corrected three-tier logic
3. Add `parseAdvancedMemoryConfig` for Level 3 configurations
4. Implement validation logic with clear error messages for configuration mistakes
5. Add smart defaults for modes and templates
6. Create comprehensive unit tests covering all configuration patterns and error cases

## Acceptance Criteria

- [ ] Level detection follows corrected logic: memories field type determines level
- [ ] Level 2 correctly requires memory: true + memories array + memory_key
- [ ] Level 3 correctly parses full MemoryReference objects
- [ ] Validation provides helpful suggestions for common configuration errors

## Testing Requirements

* Unit tests for all three configuration levels with correct YAML structures
* Error case tests with validation message verification
* Edge case tests for malformed configurations
* Coverage target: 90%

## Review Checklist

- [ ] Configuration parsing matches Tech Spec logic exactly
- [ ] Error messages are developer-friendly and actionable
- [ ] Smart defaults reduce configuration burden
- [ ] All configuration patterns from PRD examples work correctly

## Configuration Level Detection Logic

**Level 1: Direct Memory ID Reference**

```yaml
# Example: memory: "customer-support-context"
memory: "memory-id"
memory_key: "support-{{ .workflow.input.conversationId }}"
```

**Level 2: Simple Multi-Memory**

```yaml
# Example: memory: true + memories: [...] + memory_key
memory: true
memories:
  - customer-support-context
  - user-preferences
memory_key: "support-{{ .workflow.input.conversationId }}"
```

**Level 3: Advanced Configuration**

```yaml
# Example: memories: [{id, mode, key}]
memories:
  - id: customer-support-context
    mode: read-write
    key: "support-{{ .workflow.input.conversationId }}"
  - id: user-preferences
    mode: read-only
    key: "prefs-{{ .workflow.input.userId }}"
```

## Resolution Algorithm

1. Check if `memories` field exists and its type
2. If `memories` is `[]interface{}` → Level 3 (Advanced)
3. If `memories` is `[]string` and `memory: true` → Level 2 (Multi-Simple)
4. If `memory` is `string` → Level 1 (Direct ID)
5. If `memory` is `false` or `nil` → No memory configuration
6. Otherwise → Configuration error with helpful message

**Complexity**: 4  
**Domain**: engine/memory
